### PR TITLE
Small fixup to text size

### PR DESCRIPTION
**Pull request by tallytalwar**
size is a property of font and not of text

### CODE REVIEW

**Comment by tallytalwar** [comment]
@nvkelso A very small fix here.

**Comment by nvkelso** [comment]
While this is more correct, it also could have unforeseen consequences – there are many bugs related to text size in the current stylesheet and merging this may exacerbate that visually. 

I'd prefer not merging this until the `pois_*` layer can be refactored instead.

**Comment by nvkelso** [comment]
(Otherwise a good find – will it work in Tangram ES without the merge?)

**Comment by tallytalwar** [comment]
Yes it will work on tangram-es without the merge.

I am seeing similar `text:size` issues on other house styles. Will hold on filing PR for those.

**Comment by nvkelso** [comment]
Yeah, those PRs would just be throw away work.

**Comment by nvkelso** [comment]
This override is no longer present in Bubble Wrap. I'd rather pursue this fix via https://github.com/tangrams/zinc-style/issues/14.

**Pull request closed without merging**
